# --------------------------------
# NewConnect Configuration File
# --------------------------------

# The IP address that will listen for connections
address: 0.0.0.0

# The port that will listen for connections
port: 19132

# If debug messages should be sent through console
debug-mode: false

# Maximum amount of players that can connect
max-players: 500

# MOTD to display
motd: "NewConnect Proxy"
#Sub-MOTD to display. Will be "NewConnect" by default if left blank
submotd: "NewConnnect"

# Welcome message file, if file exists and is not empty this will show on join
# This is loaded live so will update without a server restart
welcome-file: welcome.txt

# Config for the Geyser listener
geyser:
  # If password authentication should be allowed in online mode.
  allow-password-authentication: false

  # If debug messages should be sent through console, has to be enabled in both places to work
  debug-mode: false

  saved-user-logins:
    - ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername
    - ThisOtherExampleUsernameShouldAlsoBeLongEnough

# A global list of servers sent to all clients
# NOTE: Java Edition server are in beta.
servers:
  - name: The Hive
    address: 167.114.81.89
    port: 19132
    bedrock: true
    category: BEDROCK
    imageUrl: 'https://i.imgur.com/VQJW6XG.png'

  - name: CubeCraft PE
    address: 94.23.159.81
    port: 19132
    bedrock: true
    category: BEDROCK
    imageUrl: 'https://www.cubecraft.net/attachments/q3pmrsod_400x400-png.53219/'

  - name: Galaxite
    address: 54.39.243.199
    port: 19132
    bedrock: true
    category: BEDROCK
    imageUrl: 'https://pbs.twimg.com/profile_images/1275867042583896066/UMPF5nTM_400x400.jpg'

  - name: Lifeboat Network
    address: 63.143.54.198
    port: 19132
    bedrock: true
    category: BEDROCK
    imageUrl: 'https://lbsg.net/wp-content/uploads/2017/06/lifeboat-square.png'

  - name: Mineplex
    address: 108.178.12.38
    port: 19132
    bedrock: true
    category: BEDROCK
    imageUrl: 'https://www.mineplex.com/assets/www-mp/img/footer/footer_smalllogo.png'

  - name: Mineplex
    address: 173.236.67.11
    port: 25565
    bedrock: false
    category: JAVA
    imageUrl: 'https://www.mineplex.com/assets/www-mp/img/footer/footer_smalllogo.png'

  - name: Hypixel
    address: 209.222.114.58
    port: 25565
    bedrock: false
    category: JAVA
    imageUrl: 'https://api.minetools.eu/favicon/mc.hypixel.net/25565'

  - name: Hycraft
    address: 149.56.152.187
    port: 25565
    bedrock: false
    category: JAVA
    imageUrl: 'https://api.minetools.eu/favicon/mc.hycraft.us/25565'

  - name: MineVille
    address: 52.234.130.255
    port: 19132
    bedrock: true
    category: BEDROCK
    imageUrl: 'https://pbs.twimg.com/profile_images/1332400307050045441/MHQvGEUP_400x400.jpg'

  - name: Pixel Paradise
    address: 40.87.84.59
    port: 19132
    bedrock: true
    category: BEDROCK
    imageUrl: 'https://xforgeassets001.xboxlive.com/pf-title-b63a0803d3653643-20ca2/fa7681c4-673d-40e4-9b6a-61d5d0f93d14/PixelParadise.jpg'

  - name: Official Geyser Test Server
    address: test.geysermc.org
    port: 19132
    bedrock: true
    category: GEYSER
    imageUrl: 'https://geysermc.org/android-chrome-192x192.png'

custom-servers:
  # Should custom servers be enabled for users
  enabled: true

  # Max amount of custom servers per user
  max: 10

  # Storage engine for custom servers
  # Can be json, sqlite, mysql
  storage-type: json

  # Connection details for the mysql storage type
  mysql:
    user: "new_connect"
    pass: ""
    database: "new_connect"
    host: "localhost"
    port: 3306

# Enable virtual hosts to be specified to skip the server list
# Allows people to connect using addresses like
#   hypixel.net._p25565.example.com
#   hypixel.net.example.com
#   hypixel.net._o.example.com    - For offline mode
vhost:
  # Should this be enabled
  enabled: false

  # The base domain pointing to the server
  base-domain: example.com
